/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.castanha;

import com.jcraft.jsch.*;
import java.io.IOException;
import java.io.InputStream;
import br.com.castanha.JOptionPane;

/**
 *
 * @author valmir.oliveira
 */
public class Caixa15 extends javax.swing.JFrame {

    /**
     * Creates new form ComandosPdvs
     */
    public Caixa15() {
        initComponents();
        ModernUi.styleCommandWindow(this, btnkillall, btnticket, btnreboot, btndisco);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        btnkillall = new javax.swing.JButton();
        btnticket = new javax.swing.JButton();
        btnreboot = new javax.swing.JButton();
        btndisco = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Comandos do caixa 15 (PDV215)");
        setResizable(false);

        btnkillall.setText("Destrava PDV");
        btnkillall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkillallActionPerformed(evt);
            }
        });

        btnticket.setText("Destrava Ticket");
        btnticket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnticketActionPerformed(evt);
            }
        });

        btnreboot.setText("Reinicia o PDV");
        btnreboot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrebootActionPerformed(evt);
            }
        });

        btndisco.setText("Esvaziar disco");
        btndisco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndiscoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Clique em um dos botões ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setText("Para executar um dos comandos no pdv");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnticket)
                            .addComponent(btnkillall))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnreboot)
                            .addComponent(btndisco))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnkillall)
                    .addComponent(btnreboot))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnticket)
                    .addComponent(btndisco))
                .addGap(48, 48, 48))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnkillallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkillallActionPerformed
        // Comando killall para destravar o pdv
        String host = "192.168.1.115";
        String user = AppConfig.getSshUser();
        String password = AppConfig.getSshPassword();

        try {
            JSch jsch = new JSch();
            Session session = jsch.getSession(user, host, 22);
            session.setPassword(password);
            session.setConfig("StrictHostKeyChecking", "no");
            session.connect();

            // Comandos a serem executados no servidor remoto
            String command1 = "killall -9 venditor";
            String command2 = "tail -f /var/log/display.log";

            // Cria um canal SSH para executar comandos no servidor remoto
            Channel channel = session.openChannel("exec");
            ((ChannelExec) channel).setCommand(command1 + ";" + command2);
            channel.setInputStream(null);
            ((ChannelExec) channel).setErrStream(System.err);

            // Obtém a saída dos comandos executados no servidor remoto
            InputStream in = channel.getInputStream();
            channel.connect();

            byte[] tmp = new byte[1024];
            while (true) {
                while (in.available() > 0) {
                    int i = in.read(tmp, 0, 1024);
                    if (i < 0) {
                        break;
                    }
                    
                    System.out.print(new String(tmp, 0, i));
                    channel.disconnect();
                    JOptionPane.showMessageDialog(null, "Programa executado com sucesso");

                }
                
                 if (channel.isClosed()) {
                    if (in.available() > 0) {
                        continue;
                    }
                    System.out.println("exit-status: " + channel.getExitStatus());
                    break;
                }
                try {
                    Thread.sleep(1000);
                } catch (Exception ee) {
                }
            }
            channel.disconnect();
            session.disconnect();
        } catch (JSchException e) {
            JOptionPane.showMessageDialog(null, "Erro ao tentar acessar o pdv \nContate o administrador de rede!");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, e + "Erro Contate o administrador de rede!");
        }
    }//GEN-LAST:event_btnkillallActionPerformed

    private void btnrebootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrebootActionPerformed
        // Executa o comanando reboot
        String host = "192.168.1.115";
        String user = AppConfig.getSshUser();
        String password = AppConfig.getSshPassword();

        try {
            JSch jsch = new JSch();
            Session session = jsch.getSession(user, host, 22);
            session.setPassword(password);
            session.setConfig("StrictHostKeyChecking", "no");
            session.connect();

            // Comandos a serem executados no servidor remoto
            String command1 = "reboot";

            // Cria um canal SSH para executar comandos no servidor remoto
            Channel channel = session.openChannel("exec");
            ((ChannelExec) channel).setCommand(command1);
            channel.setInputStream(null);
            ((ChannelExec) channel).setErrStream(System.err);

            // Obtém a saída dos comandos executados no servidor remoto
            InputStream in = channel.getInputStream();
            channel.connect();

            byte[] tmp = new byte[1024];
            while (true) {
                while (in.available() > 0) {
                    int i = in.read(tmp, 0, 1024);
                    if (i < 0) {
                        break;
                    }
                    System.out.print(new String(tmp, 0, i));
                    channel.disconnect();
                    JOptionPane.showMessageDialog(null, "Programa executado com sucesso");

                }
                if (channel.isClosed()) {
                    if (in.available() > 0) {
                        continue;
                    }
                    JOptionPane.showMessageDialog(null, "Programa executado com sucesso");
                    System.out.println("exit-status: " + channel.getExitStatus());
                    break;
                }
                try {
                    Thread.sleep(1000);
                } catch (Exception ee) {
                }
            }
            channel.disconnect();
            session.disconnect();
        } catch (JSchException e) {
            JOptionPane.showMessageDialog(null, "Erro ao tentar acessar o pdv \nContate o administrador de rede!");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, e + "Erro Contate o administrador de rede!");
        }
    }//GEN-LAST:event_btnrebootActionPerformed

    private void btnticketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnticketActionPerformed
        // executa o comando para destravar o Ticket
        String host = "192.168.1.115";
        String user = AppConfig.getSshUser();
        String password = AppConfig.getSshPassword();

        try {
            JSch jsch = new JSch();
            Session session = jsch.getSession(user, host, 22);
            session.setPassword(password);
            session.setConfig("StrictHostKeyChecking", "no");
            session.connect();

            // Comandos a serem executados no servidor remoto
            String command1 = "cd /var/venditor/SND && rm possync.lck && cd.. && cd RCV && rm possync.lck";

            // Cria um canal SSH para executar comandos no servidor remoto
            Channel channel = session.openChannel("exec");
            ((ChannelExec) channel).setCommand(command1);
            channel.setInputStream(null);
            ((ChannelExec) channel).setErrStream(System.err);

            // Obtém a saída dos comandos executados no servidor remoto
            InputStream in = channel.getInputStream();
            channel.connect();

            byte[] tmp = new byte[1024];
            while (true) {
                while (in.available() > 0) {
                    int i = in.read(tmp, 0, 1024);
                    if (i < 0) {
                        break;
                    }
                    System.out.print(new String(tmp, 0, i));
                    channel.disconnect();
                    JOptionPane.showMessageDialog(null, "Programa executado com sucesso");

                }
                if (channel.isClosed()) {
                    if (in.available() > 0) {
                        continue;
                    }
                    JOptionPane.showMessageDialog(null, "Programa executado com sucesso");
                    System.out.println("exit-status: " + channel.getExitStatus());
                    break;
                }
                try {
                    Thread.sleep(1000);
                } catch (Exception ee) {
                }
            }
            channel.disconnect();
            session.disconnect();
        } catch (JSchException e) {
            JOptionPane.showMessageDialog(null, "Erro ao tentar acessar o pdv \nContate o administrador de rede!");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, e + "Erro Contate o administrador de rede!");
        }
    }//GEN-LAST:event_btnticketActionPerformed

    private void btndiscoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndiscoActionPerformed
        // Executa o comando para esvaziar o disco
        String host = "192.168.1.115";
        String user = AppConfig.getSshUser();
        String password = AppConfig.getSshPassword();

        try {
            JSch jsch = new JSch();
            Session session = jsch.getSession(user, host, 22);
            session.setPassword(password);
            session.setConfig("StrictHostKeyChecking", "no");
            session.connect();

            // Comandos a serem executados no servidor remoto
            String command1 = "cd /var/venditor/bin && ./prunepos.sh";

            // Cria um canal SSH para executar comandos no servidor remoto
            Channel channel = session.openChannel("exec");
            ((ChannelExec) channel).setCommand(command1);
            channel.setInputStream(null);
            ((ChannelExec) channel).setErrStream(System.err);

            // Obtém a saída dos comandos executados no servidor remoto
            InputStream in = channel.getInputStream();
            channel.connect();

            byte[] tmp = new byte[1024];
            while (true) {
                while (in.available() > 0) {
                    int i = in.read(tmp, 0, 1024);
                    if (i < 0) {
                        break;
                    }
                    System.out.print(new String(tmp, 0, i));
                    channel.disconnect();
                    JOptionPane.showMessageDialog(null, "Programa executado com sucesso");

                }
                if (channel.isClosed()) {
                    if (in.available() > 0) {
                        continue;
                    }
                    JOptionPane.showMessageDialog(null, "Programa executado com sucesso");
                    System.out.println("exit-status: " + channel.getExitStatus());
                    break;
                }
                try {
                    Thread.sleep(1000);
                } catch (Exception ee) {
                }
            }
            channel.disconnect();
            session.disconnect();
        } catch (JSchException e) {
            JOptionPane.showMessageDialog(null, "Erro ao tentar acessar o pdv \nContate o administrador de rede!");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, e + "Erro Contate o administrador de rede!");
        }
    }//GEN-LAST:event_btndiscoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Caixa15.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Caixa15.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Caixa15.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Caixa15.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Caixa15().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndisco;
    private javax.swing.JButton btnkillall;
    private javax.swing.JButton btnreboot;
    private javax.swing.JButton btnticket;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
