/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.castanha;

import com.sun.source.tree.CatchTree;
import com.sun.source.tree.TryTree;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author valmir.oliveira
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
        ModernUi.styleLogin(this, jLabel2, jLabel3, passwsenha, btnentra);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnentra = new javax.swing.JButton();
        passwsenha = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela de Login");
        setResizable(false);

        jLabel2.setText("Senha");

        btnentra.setText("Entra");
        btnentra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnentraActionPerformed(evt);
            }
        });
        btnentra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnentraKeyPressed(evt);
            }
        });

        passwsenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwsenhaKeyPressed(evt);
            }
        });

        jLabel3.setText("Digite a sua senha");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnentra)
                    .addComponent(passwsenha, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwsenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(33, 33, 33)
                .addComponent(btnentra)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnentraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnentraActionPerformed
// Função da tecla enter no botão
        
            if (AppConfig.getLoginPins().contains(new String(passwsenha.getPassword()))) {
                DestravaPdvs principal = new DestravaPdvs();
                principal.setVisible(true);
                this.dispose();

            } else {
                JOptionPane.showMessageDialog(null, "Senha incorreta, verifique e tente novamente ");
            }
    }//GEN-LAST:event_btnentraActionPerformed

    private void btnentraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnentraKeyPressed
        // Função da tecla enter no botão
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (AppConfig.getLoginPins().contains(new String(passwsenha.getPassword()))) {
                DestravaPdvs principal = new DestravaPdvs();
                principal.setVisible(true);
                this.dispose();

            } else {
                JOptionPane.showMessageDialog(null, "Senha incorreta, verifique e tente novamente ");
            }
        }

    }//GEN-LAST:event_btnentraKeyPressed

    private void passwsenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwsenhaKeyPressed
        // Metodo que compara o login e senha
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
        if (AppConfig.getLoginPins().contains(new String(passwsenha.getPassword()))) {
            DestravaPdvs principal = new DestravaPdvs();
            principal.setVisible(true);
            this.dispose();

        } else {
            JOptionPane.showMessageDialog(null, "Senha incorreta, verifique e tente novamente");
        }
        }
    }//GEN-LAST:event_passwsenhaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnentra;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField passwsenha;
    // End of variables declaration//GEN-END:variables
}
